### ISSUE TITLE
Pasting text with newlines near end of KMemo 

### ISSUE THREAD

**Issue by davidbannon** [kryslt/KControls#1]
Wow, on github !   How good is that ?
I just saw your message re the bug report I logged on bitbucket.  I cannot logon there anymore so cannot screen scrape, to you want the details again ?  Attached is the patch (or do you want a pull request ?).

Davo
[kmemo_paste_text.tar.gz](https://github.com/kryslt/KControls/files/4053571/kmemo_paste_text.tar.gz)

**Comment by kryslt** [comment]
Fixed in 431a740fbd54a1728c74f5e8af1f43a9def71e56. 
Thank you for the patch.

Bitbucket drops Mercurial support soon.
But they don't provide simple one click converter from Mercurial to Git system.
To keep the repo where it is (with all commits, issues etc.) but only change VCS.
So farewell Atlassian!
Github is MS but at least they provide simple one click import, the easiest I could find.
And is overall better than Bitbucket IMO.
