### ISSUE TITLE
GTK2: Texts vertical offset is wrong when zoom > 1

### ISSUE THREAD

**Issue by biloky** [kryslt/KControls#66]
In the test project, try changing zoom to > 2, the horizontal line is in the
correct vertical position but the texts are not.

In LCL-GTK2, texts are not scaled as bitmaps, but instead, fonts' sizes are 
changed to the nearest size for that zoom. So if the font is bigger in 
2x zoom, `GetFontAscent()` will return a bigger `tmAscent` value, in which 
it should not since the font size is technically not changed but only scaled.

And `TKMemoTextBlock.WordPaintToCanvas.AdjustBaseLine()` uses `GetFontAscent() `
to compute the proper baseline.

This bug does not exists under QT5 and Win32
[kcontrols-test-01.zip](https://github.com/user-attachments/files/17340930/kcontrols-test-01.zip)

**Comment by kryslt** [comment]
Looks like to be a LCL GTK2 bug, the API should work the same in all widgetsets...

**Comment by biloky** [comment]
Ok, I'll try to make a bugreport there.  Thanks.

**Comment by kryslt** [comment]
Yep, this must be some new GTK2 bug.
Because I think this was ok in older LCL versions.
Even print previews do not scale properly now.
There is no GTK2 specific code, however.
GetFontAscent just calls GetTextMetrics API function and grabs the tmAscent field, which is well described:
(https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.ole.interop.textmetricw.tmascent?view=visualstudiosdk-2022)
The font sizes and all corresponding calculations should be the same for all widgetsets, that's how LCL widgetsets should work.
Will investigate further.

**Comment by kryslt** [comment]
Ok, this is a GTK2 bug. 
Unfortunately there are other serious bugs in the LCL.
Eg. Cocoa (MAC) cannot scale the document at all. 
This cannot be fixed at the KControls level.

**Comment by biloky** [comment]
Bug report: https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/41196

Thanks.
